services:
  - type: web
    name: medusa-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDUSA_ADMIN_CORS
        value: '*'
      - key: MEDUSA_STORE_CORS
        value: '*'
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL_HERE
